name:                ismirRep
version:             0.1.0.0
github:              "githubuser/ismirRep"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ismirRep#readme>

dependencies:
- base >= 4.7 && < 5
- singletons
- text
- singleton-nats
- ghc-typelits-natnormalise
- vector-sized
- monad-bayes
- generics-sop
- vector
- statistics
- mmorph
- HList
- random
- containers
- extra
- transformers
# - overloaded
- diagrams-lib
# - lazyppl
- semirings
- MemoTrie
- musicology-pitch
- aeson
- megaparsec
- recursion-schemes
- data-fix
- split


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ismirRep-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ismirRep

tests:
  ismirRep-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ismirRep
